FROM node:18

# Define a pasta de trabalho no container
WORKDIR /app

# Copia os arquivos de dependência e instala
COPY package*.json ./
RUN npm install

# Copia o restante dos arquivos para dentro do container
COPY . .

# Expõe a porta configurada (assumindo que config.port é 3000)
EXPOSE 3000

# Iniciar com nodemon (instale localmente ou globalmente)
CMD ["node", "src/server.js"]
