services:

  # API Gateway Node.js
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "3000:3000"
    environment:
      AUTH_MS_URL: http://auth-service:8081
      JWT_SECRET: ${JWT_SECRET}
    env_file:
      - .env
    depends_on:
      - auth-service
    networks:
      - hospital-network

  # Auth Service Spring Boot
  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://auth-db:5432/authdb
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
    env_file:
      - .env
    depends_on:
      - auth-db
    networks:
      - hospital-network

  auth-db:
    image: postgres:15
    container_name: auth-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - ./auth-service/init/init.sql:/docker-entrypoint-initdb.d/init.sql 
      - auth-data:/var/lib/postgresql/data 
    env_file:
      - .env
    networks:
      - hospital-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    env_file:
      - .env
    networks:
      - hospital-network

volumes:
  auth-data:

networks:
  hospital-network:
    driver: bridge
  