services:
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
    volumes:
      - ./api-gateway:/app
      - /app/node_modules
    networks:
      - hospital-network
    env_file:
      - ./api-gateway/.env

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-db:5432/authdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: faty0910
    volumes:
      - ./auth-service:/app
      - ~/.m2:/root/.m2
    env_file:
      - ./auth-service/.env
    networks:
      - hospital-network
    depends_on:
      - auth-db

  auth-db:
    image: postgres:15
    container_name: auth-db
    restart: always
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: faty0910
    ports:
      - "5433:5432"
    volumes:
      - ./auth-service/init-db/init.sql:/docker-entrypoint-initdb.d/init.sql 
      - auth-data:/var/lib/postgresql/data
    networks:
      - hospital-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@hospital.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    networks:
      - hospital-network

volumes:
  auth-data:

networks:
  hospital-network:
    driver: bridge
