CREATE TABLE IF NOT EXISTS account (
    id SERIAL PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    senha VARCHAR(64) NOT NULL,
    cpf VARCHAR(11) NOT NULL UNIQUE,
    tipo VARCHAR(50) NOT NULL
);
